# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

include: ["_pages"]

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      toc: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

title: ideal-octo-enigma
title_separator: "|"
subtitle: "Version 2.0"
name: "Ideal Octo Enigma"
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: zerobabble
github_username: zerobabble
repository: "zerobabble/ideal-octo-enigma"

# search feature
search: true
lunr:
  search_within_pages: true

author:
  name: "zerobabble"
  avatar: "/assets/images/avatar-96x96.png"
  bio: "My awesome biography constrained to a sentence or two goes here."
  location: "Somewhere, USA, Earth"

# Build settings
# theme: minima
# theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# theme: jekyll-theme-architect
# theme: jekyll-theme-cayman
# theme: jekyll-theme-dinky
# theme: jekyll-theme-hacker
# theme: jekyll-theme-leap-day
# theme: jekyll-theme-merlot
# theme: jekyll-theme-midnight
# theme: jekyll-theme-minimal
# theme: jekyll-theme-modernist
# theme: jekyll-theme-primer
# theme: jekyll-theme-slate
# theme: jekyll-theme-tactile
# theme: jekyll-theme-time-machine

# remote_theme: pages-themes/architect@v0.2.0
remote_theme: mmistakes/minimal-mistakes
# remote_theme: joaomlneto/jekyll-multiverse-template
# remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
